// <auto-generated />
using System;
using CinehubBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinehubBack.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250327230050_MovieEntity")]
    partial class MovieEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CinehubBack.Model.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Adult")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("adult");

                    b.Property<string>("BackPhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("KeyWords")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("keywords");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("original_language");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("overview");

                    b.Property<decimal>("Popularity")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("popularity");

                    b.Property<string>("PosterPhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("backdrop_path");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_date");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("revenue");

                    b.Property<int>("RunTime")
                        .HasColumnType("int")
                        .HasColumnName("runtime");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tagline");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<decimal>("VoteAverage")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("vote_average");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int")
                        .HasColumnName("vote_count");

                    b.HasKey("Id");

                    b.ToTable("movie", (string)null);
                });

            modelBuilder.Entity("CinehubBack.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
